# Generated by Django 4.2.5 on 2025-11-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OSMFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_file", models.FileField(upload_to="osm_files/original/")),
                (
                    "processed_file",
                    models.FileField(
                        blank=True, null=True, upload_to="osm_files/processed/"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("file_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("error", "Error"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("min_lat", models.FloatField(blank=True, null=True)),
                ("max_lat", models.FloatField(blank=True, null=True)),
                ("min_lon", models.FloatField(blank=True, null=True)),
                ("max_lon", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
