# Generated by Django 4.2.26 on 2025-11-16 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("osm_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComputationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_vehicles", models.IntegerField()),
                ("computation_time", models.FloatField(help_text="Time in seconds")),
                (
                    "total_length_m",
                    models.FloatField(help_text="Total road length in meters"),
                ),
                ("total_nodes", models.IntegerField()),
                ("total_roads", models.IntegerField()),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "osm_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="computation_logs",
                        to="osm_app.osmfile",
                    ),
                ),
            ],
            options={
                "ordering": ["-computed_at"],
                "indexes": [
                    models.Index(
                        fields=["osm_file", "-computed_at"],
                        name="osm_app_com_osm_fil_cab689_idx",
                    ),
                    models.Index(
                        fields=["num_vehicles"], name="osm_app_com_num_veh_331cad_idx"
                    ),
                ],
            },
        ),
    ]
