# Generated by Django 4.2.5 on 2025-11-16 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("osm_app", "0002_computationlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="WardConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_wards", models.IntegerField()),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("auto", "Auto (Square Grid)"),
                            ("horizontal", "Horizontal Strips"),
                            ("vertical", "Vertical Strips"),
                        ],
                        default="auto",
                        max_length=20,
                    ),
                ),
                ("rows", models.IntegerField(help_text="Number of rows in ward grid")),
                (
                    "cols",
                    models.IntegerField(help_text="Number of columns in ward grid"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "osm_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ward_configs",
                        to="osm_app.osmfile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ward_number", models.IntegerField()),
                ("min_lat", models.FloatField()),
                ("max_lat", models.FloatField()),
                ("min_lon", models.FloatField()),
                ("max_lon", models.FloatField()),
                ("centroid_lat", models.FloatField()),
                ("centroid_lon", models.FloatField()),
                ("row", models.IntegerField()),
                ("col", models.IntegerField()),
                ("num_vehicles", models.IntegerField(default=1)),
                (
                    "routes_data",
                    models.JSONField(
                        blank=True, help_text="Computed routes for this ward", null=True
                    ),
                ),
                (
                    "geojson_file",
                    models.FileField(blank=True, null=True, upload_to="ward_geojson/"),
                ),
                ("total_distance_m", models.FloatField(blank=True, null=True)),
                ("computation_time", models.FloatField(blank=True, null=True)),
                ("computed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wards",
                        to="osm_app.wardconfiguration",
                    ),
                ),
            ],
            options={
                "ordering": ["config", "ward_number"],
                "indexes": [
                    models.Index(
                        fields=["config", "ward_number"],
                        name="osm_app_war_config__794847_idx",
                    )
                ],
                "unique_together": {("config", "ward_number")},
            },
        ),
    ]
