# Generated by Django 4.2.5 on 2025-11-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("osm_app", "0003_wardconfiguration_ward"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ward",
            name="col",
        ),
        migrations.RemoveField(
            model_name="ward",
            name="geojson_file",
        ),
        migrations.RemoveField(
            model_name="ward",
            name="routes_data",
        ),
        migrations.RemoveField(
            model_name="ward",
            name="row",
        ),
        migrations.RemoveField(
            model_name="ward",
            name="total_distance_m",
        ),
        migrations.RemoveField(
            model_name="wardconfiguration",
            name="cols",
        ),
        migrations.RemoveField(
            model_name="wardconfiguration",
            name="layout",
        ),
        migrations.RemoveField(
            model_name="wardconfiguration",
            name="rows",
        ),
        migrations.AddField(
            model_name="ward",
            name="area_km2",
            field=models.FloatField(
                default=0.0, help_text="Ward area in square kilometers"
            ),
        ),
        migrations.AddField(
            model_name="ward",
            name="routes_geojson",
            field=models.JSONField(
                blank=True, help_text="Computed routes in GeoJSON format", null=True
            ),
        ),
        migrations.AddField(
            model_name="ward",
            name="total_length_m",
            field=models.FloatField(
                default=0.0, help_text="Total road length in meters"
            ),
        ),
        migrations.AddField(
            model_name="ward",
            name="total_nodes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ward",
            name="total_roads",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wardconfiguration",
            name="area_per_ward_km2",
            field=models.FloatField(
                default=0.0, help_text="Average area per ward in square kilometers"
            ),
        ),
        migrations.AddField(
            model_name="wardconfiguration",
            name="grid_cols",
            field=models.IntegerField(
                blank=True, help_text="Number of columns in grid layout", null=True
            ),
        ),
        migrations.AddField(
            model_name="wardconfiguration",
            name="grid_rows",
            field=models.IntegerField(
                blank=True, help_text="Number of rows in grid layout", null=True
            ),
        ),
        migrations.AddField(
            model_name="wardconfiguration",
            name="total_area_km2",
            field=models.FloatField(
                default=0.0, help_text="Total area in square kilometers"
            ),
        ),
        migrations.AddField(
            model_name="wardconfiguration",
            name="ward_dimensions_km",
            field=models.CharField(
                blank=True,
                help_text="Approximate dimensions (e.g., '1.43 × 1.28 km')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="wardconfiguration",
            name="ward_layout",
            field=models.CharField(
                choices=[("auto_grid", "Auto (Square Grid)"), ("manual", "Manual")],
                default="auto_grid",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="ward",
            name="centroid_lat",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="ward",
            name="centroid_lon",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="ward",
            name="computation_time",
            field=models.FloatField(blank=True, help_text="Time in seconds", null=True),
        ),
        migrations.AlterField(
            model_name="ward",
            name="max_lat",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="ward",
            name="max_lon",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="ward",
            name="min_lat",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="ward",
            name="min_lon",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="ward",
            name="num_vehicles",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ward",
            name="ward_number",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="wardconfiguration",
            name="num_wards",
            field=models.IntegerField(default=4),
        ),
        migrations.AddIndex(
            model_name="wardconfiguration",
            index=models.Index(
                fields=["osm_file", "-created_at"],
                name="osm_app_war_osm_fil_b6859d_idx",
            ),
        ),
    ]
