# Generated by Django 4.2.5 on 2025-11-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("osm_app", "0004_remove_ward_col_remove_ward_geojson_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ward",
            name="population",
            field=models.IntegerField(
                default=0, help_text="Estimated population count"
            ),
        ),
        migrations.AddField(
            model_name="ward",
            name="population_density_per_km2",
            field=models.FloatField(
                default=0.0, help_text="Population per square kilometer"
            ),
        ),
        migrations.AddField(
            model_name="ward",
            name="population_source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Entry"),
                    ("worldpop", "WorldPop Raster"),
                    ("osm", "OSM Buildings"),
                ],
                default="worldpop",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ward",
            name="vehicle_capacity_kg",
            field=models.FloatField(default=1000.0, help_text="Vehicle capacity (kg)"),
        ),
        migrations.AddField(
            model_name="ward",
            name="waste_per_capita_kg",
            field=models.FloatField(
                default=0.5, help_text="Waste per person per day (kg)"
            ),
        ),
    ]
