# Generated by Django 4.2.26 on 2025-11-19 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("osm_app", "0005_ward_population_ward_population_density_per_km2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Depot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.TextField(blank=True)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                (
                    "capacity_kg",
                    models.FloatField(
                        default=10000.0, help_text="Daily handling capacity (kg)"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="ward",
            name="depot_distance_km",
            field=models.FloatField(
                default=0.0, help_text="Distance from ward centroid to depot (km)"
            ),
        ),
        migrations.AddField(
            model_name="ward",
            name="has_valid_data",
            field=models.BooleanField(
                default=True, help_text="Ward has sufficient data for routing"
            ),
        ),
        migrations.AddField(
            model_name="ward",
            name="is_connected",
            field=models.BooleanField(
                default=True, help_text="All roads in ward form a connected network"
            ),
        ),
        migrations.AddField(
            model_name="ward",
            name="last_validated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ward",
            name="validation_warnings",
            field=models.JSONField(
                blank=True, default=list, help_text="List of validation warnings"
            ),
        ),
        migrations.AddField(
            model_name="ward",
            name="assigned_depot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wards",
                to="osm_app.depot",
            ),
        ),
    ]
